version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app/backend
      - ./frontend/dist:/app/frontend/dist
    environment:
      - FLASK_ENV=development
